### ISSUE TITLE
Xenomorphs are broken.

### ISSUE THREAD

**Issue by Mindtrixx** [LLA-Gaming/SS13#115]
Aliens vent crawl doesn't show in action menu anymore (have to alt-click?)

Aliens can't remove items from people.

Aliens need a disarm nerf, at least a small chance to get up unless two xenos are there.

**Comment by QuantumWings** [comment]
I think this needs to be split up into a bug and a suggestion section.
One of these issues is a bug, the rest are balancing.

**Comment by FlavoredCactus** [comment]
Please do as quantumwings suggested and split this up into 2 different issue trackers.
