### ISSUE TITLE
I.loc = dest Considered Harmful

### ISSUE THREAD

**Issue by QuantumWings** [LLA-Gaming/SS13#161]
Using "I.loc = dest" is the underlying cause of the mister bug. Using this instead of I.Move(dest) caused the funkyness that let a single mister appearer in multiple locations.

Fixing this may cause more bugs than it solves, but it is worth keeping this in mind if any other issues involving single instances of an item appearing in multiple locations.

**Comment by FlavoredCactus** [comment]
Marking this as information to keep around later but closing to organize open issues.
