### ISSUE TITLE
Changeling regeneration

### ISSUE THREAD

**Issue by Stingray540** [LLA-Gaming/SS13#185]
Objects or Mechanics Involved:Changeling regeneration
Brief Description (include as much detail as possible):While dead as a changeling and regeneration was ready, I was going to re-adapt to get a ling space suit. When I re-adapted, the regenerate button dissapeared, and I could not regen again
What did you expect to happen?:Being able to regen
What happened instead?:I couldn't regen at all
Has this occurred before?:No
What were you doing beforehand?:Being killed and locked in a locker that was spaced
Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.):

**Comment by FlavoredCactus** [comment]
I cant seem to reproduce this myself. and havent been since this was posted. make a new issue with some more precise steps if possible
