### ISSUE TITLE
Bug: Upgrading grab in a chair.

### ISSUE THREAD

**Issue by Sweedle** [LLA-Gaming/SS13#358]
Objects or Mechanics Involved: Upgrading a grab while buckled into a chair.
Brief Description (include as much detail as possible): I attempted to table a dead person while on the shuttle and buckled into an office chair, I could get the basic grab, but I couldn't upgrade.
What did you expect to happen?: My grab level to change to "aggressive"
What happened instead?: I 'dropped' the grab as if I'd dropped an item.
Has this occurred before?: Not to me
What were you doing beforehand?: I just dragged the lethally injected person onto the shuttle and into the bridge.
Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.): I tested it by myself on the station and got the same result.

**Comment by FlavoredCactus** [comment]
I believe this is intended, you shouldnt be able to reinforce grabs while buckled yourself.
