### ISSUE TITLE
Colored Lighting System

### ISSUE THREAD

**Issue by TheDracheX** [LLA-Gaming/SS13#368]

**Comment by FlavoredCactus** [comment]
Test list
- [ ] APCs and lighting
- [ ] various weapon lights.
- [ ] Mass light breaking (malf power)
- [ ] Smoke's effect on lighting
- [ ] Halloween lighting disruption
- [ ] Honking Angels power disruption

**Comment by FlavoredCactus** [comment]
Things ive found list (will update as i go)
-Station is alot dimmer. seems like the small lights lighten up a lot less.

**Comment by FlavoredCactus** [comment]
WOOPS.

**Comment by Raptorblaze** [comment]
Project abandoned in favor of an alternative lighting system. Closing issue out
