### ISSUE TITLE
DEVELOPMENT-Miscellaneous Pod Issues

### ISSUE THREAD

**Issue by Flahhh-Personson** [LLA-Gaming/SS13#376]
These are small issues. I'll just post them as I find them.

Mobs don't attack or otherwise target pods (tested with Basilisk, Goliath, Carp) - **FIXED**

When a pod is fully in the dark with lights off, all tiles except the bottom left are fully visible - **Don' think that's fixable.**

Pods are able to move onto spaces with floor tiles, as long as only one of the two tiles it moves to has one. - **NOT A BUG**

The 1x1 pod does not appear to exist. - **NOT A BUG**

Pod weapon projectiles appear to manifest two tiles in front of the pod--if there is a wall or mob immediately in front, it will pass harmlessly through. - **FIXED**

**Comment by TheDracheX** [comment]
1. Adding that would require adding manual targeting to each mob, I don't think they attack mechs either.
2. I'm not sure if I can do anything about that really, just the pains of 64x64
4. Hold a wrench
5. No, those are supposed to be minimums.
6. Whoops.

**Comment by Flahhh-Personson** [comment]
Okay, evidently I'm missing something. How EXACTLY do you remove items? I've beaten a lot of pods to death with wrenches trying to figure this out.

**Comment by TheDracheX** [comment]
Open the menu and click on the name of the attachment, it should be a button and hold a wrench in your hand

**Comment by Flahhh-Personson** [comment]
I can't figure out how to open the menu from outside the pod. From inside, nothing happens.

**Comment by TheDracheX** [comment]
Multitool

**Comment by Flahhh-Personson** [comment]
Thanks! One more half-bug for you, then. Or thing I don't get. How do you put the air canister back in the pod?

**Comment by Flahhh-Personson** [comment]
Also, the power cell.

**Comment by TheDracheX** [comment]
Ctrl Click on the canister from inside the pod

**Comment by Flahhh-Personson** [comment]
Okay. It seems impossible to re-add the air can and power cell, though you've probably thought of that one already. Mobs DO target mechs--ask anyone who's ever mined in a Ripley, myself included. I'll remove all resolved issues.

**Comment by TheDracheX** [comment]
Weird...it USED to work I swear.

**Comment by Flahhh-Personson** [comment]
New issue: the external light tubes on the mining pod hangar are off--presumably because the APC doesn't cover them.
