### ISSUE TITLE
DEVELOPMENT-Nuke Ops Ship Is Escapable

### ISSUE THREAD

**Issue by Flahhh-Personson** [LLA-Gaming/SS13#378]
Objects or Mechanics Involved: The hangar for the Nuke Ops pod, and the related pod.
Brief Description (include as much detail as possible): Open the nuke ops pod door, fly it down into the forcefield, get out, go punch a pine tree.
What did you expect to happen?: Something that would prevent me from being able to leave the ship. This is only really significant as there is likely a way to get through the perimeter walls and into the CentCom area.
What happened instead?: I was able to go punch a pine tree on the exterior of the nuke ops spawn.
Has this occurred before?: Yes.
What were you doing beforehand?: Teleporting around.
Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.): Why is the pod door linked to the other door's button? Having to run across the entire ship to open the door for a few seconds seems... incorrect.

**Comment by TheDracheX** [comment]
You can leave the ship anyway, I don't think you can escape that way, the teleporter doesn't work on z 2
