### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by TheDracheX** [LLA-Gaming/SS13#383]
More Info: http://www.llagaming.net/forums/threads/space-exploration-update.4170/

**Comment by FlavoredCactus** [comment]
OMG YES

**Comment by FlavoredCactus** [comment]
[12:02:17 AM] TheDracheX: ugh
[12:02:29 AM] TheDracheX: im watching narcos first
[12:02:32 AM] TheDracheX: then ill work on templates
[12:02:35 AM] TheDracheX: you can quote me
[12:02:36 AM] TheDracheX: on that

**Comment by FlavoredCactus** [comment]
- [ ] Infinite loop bug with missing templates / incorrect sub directory named templates

**Comment by TheDracheX** [comment]
Current Bugs:
[] Placed space turfs have a greyish tint to them

**Comment by FlavoredCactus** [comment]
>Placed space turfs have a greyish tint to them
check and see if there is an AREA over it from area generation
