### ISSUE TITLE
Betrayel Gamemode

### ISSUE THREAD

**Issue by FlavoredCactus** [LLA-Gaming/SS13#389]
Idea by forum user wuufles
Copy pasted from the forums: http://www.llagaming.net/forums/threads/game-mode-betrayed-agent.4721/

> Game Mode: Betrayed Agent
> 
> Population: Available with 4 people. Cannot late join as one of these traitors.
> 
> Shitty flavour text: You are one of the Syndicate's best agents, but a double agent has betrayed you to Centcomm. It is only a matter of time until your presence is alerted to the station. Centcomm may attempt to periodically update the crew on your location while you are alive. Survive the shift so that you can find a better employer. The syndicate can only send some telecrystals at a time, but will try to make it up to you by sending more over time. You have <time> until you are betrayed.

> Description: Traitors are spawned on the station with only 1 or 2 telecrystals. More telecrystals are given to the traitor over time in deliveries of ~3 crystals every 10 minutes to a max of 12 total crystals given to a traitor. The amount of traitors spawned corresponds with the amount that would be spawned on a traitor round.

> The catch is that ~5 minutes into the round Centcomm makes an announcement revealing who the traitors are. The smaller the crew, the sooner the announcement will be made. Minimum 1 minute is given. Throughout the round a paper will be printed off on all communication consoles listing the locations of the traitors still alive, just like at round start on other rounds. This would happen every 5 to 10 minutes.

> Objectives: The objectives for the traitors are to steal an item, kill a target, and then to stay alive until the end of the round.

> End condition: Shuttle is called just like on most other round types; round ends when the shuttle reaches the station.

> Reasoning: This is designed to pit crew against antagonists to hopefully make a fast paced game mode that can work on a fairly small pop as well. Giving away the names and locations of the traitors will hopefully keep things fast-paced and prevent the round from stagnating. Rounds will probably because of the chaos.

> Traitors are given only a few telecystals at round start to keep them weak. The first few moments of the game for traitors should be used for attempting to hectically scavenge together any advantage they can, instead of murdering everyone before the warning goes off.

> Hopefully having two different objectives will keep traitors moving around, obviously there's easy ways around this when you have to steal an item you spawn with and then kill your coworker, but whatever. The assassination objective should keep people on hostile terms with the crew since they know the traitors are out to get them. None of that friendly bull shit.

> Shorter warning times on low-pop rounds should prevent a traitor from killing absolutely everyone in cold blood. Even if the traitor HoS just raided armory and has all the guns, if you know he's coming there are plenty of things you can do to go up against him even on a low-pop round. On higher pop rounds, traitors will need more time to prepare.

**Comment by FlavoredCactus** [comment]
https://github.com/LLA-Gaming/SS13/commit/94c377910f62462c7d9a7ecfa9fa6af6e7a5d7c7 good to go i think

**Comment by Flahhh-Personson** [comment]
*betrayal

**Comment by FlavoredCactus** [comment]
It was spelled fine in the commits go away.
