### ISSUE TITLE
Suggestion - Auto-Injectors and Heart Monitors

### ISSUE THREAD

**Issue by Flahhh-Personson** [LLA-Gaming/SS13#393]
Right. Two items to be used here, mostly in conjunction, but they each have a few things they can do on their own.

AUTO-INJECTORS:

These are built by wiring a syringe, at the cost of 5 lengths. When used in hand, a window comes up allowing you to add/remove a signalling mechanism (of any sort a grenade could take), or remove the syringe (probably for filling). Using a syringe on an empty injector inserts it.

When it receives a signal from whatever's attached, the injector fires, destroying the syringe and emptying its contents into whoever's holding it. This only works in hands, suit storage, pockets or the belt slot, and not while wearing a hardsuit (or anything a syringe gun couldn't get through)

HEART MONITORS:

3 of these will spawn on a table in medical (the one next to labcoat storage) at the start of the shift, and more can be built by an Autolathe for . These can be set to go off when the person holding them either is stunned, goes into crit, dies, or any combination of the three. When they fire, they activate whatever they're rigged to. On that note, they can be attached to anything a signaller could.

**Comment by FlavoredCactus** [comment]
Wuuufles said he would take this.

**Comment by FlavoredCactus** [comment]
This in
