### ISSUE TITLE
Sneakyranger's Minor Suggestions

### ISSUE THREAD

**Issue by FlavoredCactus** [LLA-Gaming/SS13#394]
Copy pasted from the forums, these are sneakyranger's minor suggestions all grouped up into 1 issue

- [x] Minor: Add an off button for the Night Vision Goggles, so if a syndie uses them and knocks out the lights he can actually use darkness effectively. Thermals have one, so why not NVG?

- [x] Medium: Add a brig door-closing button on the warden's desk that: doesn't work during greytide virus, does not work when the doors are bolted open manually, and does not open them so that there isn't any airlock shuffle like with the one near the doors themselves.

- [x] Another possible change is to allow clicking and dragging of replacement light boxes into light replacers, doing a half and half amount of whatever's in there if possible. For specific amounts one would have to do it themselves.
- [x] Another idea: grey hat for detective. Would fit with the rest of the grey stuff, and would be much better in my opinion.

**Comment by Raptorblaze** [comment]
PR #395 created to implement these objects. Once merge, I've asked Flavo to add the specific items to the ingame map as needed.

**Comment by FlavoredCactus** [comment]
complete
