### ISSUE TITLE
Wood Kudzu too strong

### ISSUE THREAD

**Issue by Wp-Ninja** [LLA-Gaming/SS13#420]
Objects or Mechanics Involved: Kudzu, strain Wooden

Brief Description (include as much detail as possible): The wooden kudzu can't be destroyed by scythes, and acts like a wall. Killing it with a welder takes 3 refills? Can't kill it with lasers either. 

What did you expect to happen?: For it to be killed by the scythe.

What happened instead?: It lived.

Has this occurred before?: Donno.

What were you doing beforehand?: Killing Kudzu

Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.):
https://gyazo.com/55086bef474572c3bf34f7aa583ffdd9

**Comment by FlavoredCactus** [comment]
Not a bug, but probably too strong. we will look into balancing

**Comment by Dtallant** [comment]
from what I remember talking to a guy a long time back about kudzu and its specials- wood kudzu is meant to be a wall, taking forever to grow. But once it does grow it is almost impossible to kill though relatively easy to detain.

**Comment by FlavoredCactus** [comment]
Its incredibly strong in the sense that it does a probability roll using the force of the weapon you use

so say a tool box is prob(10). so it really comes down to if RNG wants  you to destroy the kudzu

**Comment by FlavoredCactus** [comment]
Density removed from woodening kudzu
