### ISSUE TITLE
Z-Level Transitioning System

### ISSUE THREAD

**Issue by TheDracheX** [LLA-Gaming/SS13#433]
New system that operates on a 2x3 grid which is generated at round-start instead of randomly moving someone to a z.

E.g. a grid would look like this:

1 | 3 | 4
7 | 5 | 6

Moving north from z 1 would land you on z 7. Moving west from z 1 would land you at z 6. Horizontal movement wraps around rows, so moving east on z 6 would land you on z 1. Vertical movement does not currently wrap.

**Comment by FlavoredCactus** [comment]
This looks complete from this commit. correct me if wrong. https://github.com/LLA-Gaming/SS13/commit/172091c59eaf2e4b17daf58d17864be9cf4c0774
