### ISSUE TITLE
Various Research Bugs

### ISSUE THREAD

**Issue by Mindtrixx** [LLA-Gaming/SS13#452]
- [x] 1. Servers need to have their permissions set to allow Robotics (?), Crew Pod Hangar, and Mining Pod Hangar to sync research. Apparently this is a map issue. **CANNOT REPLICATE**

- [x] 2. /list Appears in the Robotics Fabricator after a undetermined amount of research. It has nothing in it. **FIXED**

- [x] 3. Power Cores are able to be built in a Robotics Fabricator under Power Armor Equipment after they become available in the Protolathe **INTENDED**

- [x] 4. **(Unconfirmed)** Getting Materials 7 possibly breaks syncing machines. Other possibility: I somehow screwed up the RD servers and it was just a weird bout of incompetence. Break down three One-Human boards (spawn /aimodule) to get to Materials 7. **CANNOT REPLICATE**

:dromedary_camel::whale::horse::dromedary_camel::whale::horse::dromedary_camel::whale::horse::dromedary_camel::whale::horse::dromedary_camel::whale::horse::dromedary_camel::whale::horse::dromedary_camel::whale::horse::dromedary_camel::whale::horse::dromedary_camel::whale::horse::dromedary_camel::whale::horse::dromedary_camel::whale::horse:

**Comment by FlavoredCactus** [comment]
Fixed issue number 2, the rest are intended or cant be replicated.
