### ISSUE TITLE
Bug: Holding Area ( Ninja Jail) unable to move

### ISSUE THREAD

**Issue by Kirbyroth** [LLA-Gaming/SS13#81]
Objects or Mechanics Involved: The capture net and teleporting to the holding area aka the ninja jail. Movement.
Brief Description (include as much detail as possible): When the ninja captures you are sent to the holding area at centcom but we weren't able to move at all once we were sent there.
What did you expect to happen?: Last time this happen to me i could move around though the public areas
What happened instead?: We were stuck in place unable to move from our spot or even lay down as if we were buckled to a invisible chair
Has this occurred before?: No
What were you doing beforehand?: Being captured by ninja with the capture net
Additional Information (were you any special mob, did anything prior happen? Screenshots/Logs, etc.): Was RD human. was in the capture net.

![libertys last army main server official lla center 2014-08-11 072538](https://cloud.githubusercontent.com/assets/8416510/3875711/8f9e8a46-2154-11e4-8598-a553be531e3e.png)

**Comment by FlavoredCactus** [comment]
This was fixed with another buckling issue awhile back
